---
all:
  hosts:
    master0:
      ansible_host: 10.0.80.11
      dns_name: "nyankube-master-0.c2.int.nyansq.ru"
    worker0:
      ansible_host: 10.0.80.12
      dns_name: "nyankube-worker-0.c2.int.nyansq.ru"
    worker1:
      ansible_host: 10.0.80.13
      dns_name: "nyankube-worker-1.c2.int.nyansq.ru"

  children:
    k8s_masters:
      hosts:
        master0:

    k8s_workers:
      hosts:
        worker0:
        worker1:

    k8s_fleet:
      children:
        k8s_masters:
        k8s_workers:
